# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: Hello I am Chaitanya!
  displayName: 'Run a one-line script'

steps:
- script: Hello I am Aditya!
  displayName: 'Rudra'
